//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLog.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarLog.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add vehicle.
        /// </summary>
        public static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add fuel.
        /// </summary>
        public static string AddFuel {
            get {
                return ResourceManager.GetString("AddFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add remind.
        /// </summary>
        public static string AddReminder {
            get {
                return ResourceManager.GetString("AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add service.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY CAR LOG.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle loan.
        /// </summary>
        public static string CarLoan {
            get {
                return ResourceManager.GetString("CarLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle loan account number.
        /// </summary>
        public static string CarLoanAccountNumber {
            get {
                return ResourceManager.GetString("CarLoanAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank name.
        /// </summary>
        public static string CarLoanBankName {
            get {
                return ResourceManager.GetString("CarLoanBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle loan payment.
        /// </summary>
        public static string CarLoanPayment {
            get {
                return ResourceManager.GetString("CarLoanPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compact view.
        /// </summary>
        public static string CompactView {
            get {
                return ResourceManager.GetString("CompactView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmailLabel {
            get {
                return ResourceManager.GetString("ContactEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onmydevice@gmail.com.
        /// </summary>
        public static string ContactEmailText {
            get {
                return ResourceManager.GetString("ContactEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateDisplayName {
            get {
                return ResourceManager.GetString("DateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this vehicle and all of it&apos;s history?.
        /// </summary>
        public static string DeleteCarQuestion {
            get {
                return ResourceManager.GetString("DeleteCarQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this fuel event?.
        /// </summary>
        public static string DeleteFuelEventQuestion {
            get {
                return ResourceManager.GetString("DeleteFuelEventQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this reminder?.
        /// </summary>
        public static string DeleteReminderQuestion {
            get {
                return ResourceManager.GetString("DeleteReminderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this service event?.
        /// </summary>
        public static string DeleteServiceEventQuestion {
            get {
                return ResourceManager.GetString("DeleteServiceEventQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles per gallon.
        /// </summary>
        public static string DistancePerQuantity {
            get {
                return ResourceManager.GetString("DistancePerQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg.
        /// </summary>
        public static string DistancePerQuantityShort {
            get {
                return ResourceManager.GetString("DistancePerQuantityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string DistanceShort {
            get {
                return ResourceManager.GetString("DistanceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance units.
        /// </summary>
        public static string DistanceUnits {
            get {
                return ResourceManager.GetString("DistanceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle.
        /// </summary>
        public static string EditCar {
            get {
                return ResourceManager.GetString("EditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cost.
        /// </summary>
        public static string EditCost {
            get {
                return ResourceManager.GetString("EditCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string EditDate {
            get {
                return ResourceManager.GetString("EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance.
        /// </summary>
        public static string EditDistance {
            get {
                return ResourceManager.GetString("EditDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel grade.
        /// </summary>
        public static string EditFuelGrade {
            get {
                return ResourceManager.GetString("EditFuelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch up entry (ignore).
        /// </summary>
        public static string EditIgnoreForStatisticts {
            get {
                return ResourceManager.GetString("EditIgnoreForStatisticts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last service date.
        /// </summary>
        public static string EditLastServiceDate {
            get {
                return ResourceManager.GetString("EditLastServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last service odometer.
        /// </summary>
        public static string EditLastServiceOdometer {
            get {
                return ResourceManager.GetString("EditLastServiceOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string EditMonths {
            get {
                return ResourceManager.GetString("EditMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next service odometer.
        /// </summary>
        public static string EditNextOdometer {
            get {
                return ResourceManager.GetString("EditNextOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next service date.
        /// </summary>
        public static string EditNextServiceDate {
            get {
                return ResourceManager.GetString("EditNextServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odometer.
        /// </summary>
        public static string EditOdometer {
            get {
                return ResourceManager.GetString("EditOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string EditPrice {
            get {
                return ResourceManager.GetString("EditPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recurring.
        /// </summary>
        public static string EditRecurring {
            get {
                return ResourceManager.GetString("EditRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder type.
        /// </summary>
        public static string EditReminderType {
            get {
                return ResourceManager.GetString("EditReminderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service type.
        /// </summary>
        public static string EditServiceType {
            get {
                return ResourceManager.GetString("EditServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file management.
        /// </summary>
        public static string FileManagement {
            get {
                return ResourceManager.GetString("FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel event.
        /// </summary>
        public static string FuelEvent {
            get {
                return ResourceManager.GetString("FuelEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallons.
        /// </summary>
        public static string Gallons {
            get {
                return ResourceManager.GetString("Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons.
        /// </summary>
        public static string GallonsC {
            get {
                return ResourceManager.GetString("GallonsC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        public static string GallonShort {
            get {
                return ResourceManager.GetString("GallonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insurance.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insurance policy number.
        /// </summary>
        public static string InsuranceAccountNumber {
            get {
                return ResourceManager.GetString("InsuranceAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insurance provider.
        /// </summary>
        public static string InsuranceName {
            get {
                return ResourceManager.GetString("InsuranceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insurance monthly payment.
        /// </summary>
        public static string InsurancePayment {
            get {
                return ResourceManager.GetString("InsurancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers per gallon.
        /// </summary>
        public static string KilometersPerGallon {
            get {
                return ResourceManager.GetString("KilometersPerGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kpg.
        /// </summary>
        public static string KilometersPerGallonShort {
            get {
                return ResourceManager.GetString("KilometersPerGallonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers per liter.
        /// </summary>
        public static string KilometersPerLiter {
            get {
                return ResourceManager.GetString("KilometersPerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kpl.
        /// </summary>
        public static string KilometersPerLiterShort {
            get {
                return ResourceManager.GetString("KilometersPerLiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string KilometersShort {
            get {
                return ResourceManager.GetString("KilometersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers Since Last.
        /// </summary>
        public static string KilometersSinceDisplayName {
            get {
                return ResourceManager.GetString("KilometersSinceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liters.
        /// </summary>
        public static string Liters {
            get {
                return ResourceManager.GetString("Liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        public static string LitersC {
            get {
                return ResourceManager.GetString("LitersC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lit.
        /// </summary>
        public static string LiterShort {
            get {
                return ResourceManager.GetString("LiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        public static string LoadLocal {
            get {
                return ResourceManager.GetString("LoadLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load OneDrive.
        /// </summary>
        public static string LoadOneDrive {
            get {
                return ResourceManager.GetString("LoadOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string MaintenanceDisplayName {
            get {
                return ResourceManager.GetString("MaintenanceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MenuButtonCancel {
            get {
                return ResourceManager.GetString("MenuButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string MenuButtonSave {
            get {
                return ResourceManager.GetString("MenuButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad has occurred with this entry. Please make sure all your entries are valid..
        /// </summary>
        public static string MessageErrorOccurred {
            get {
                return ResourceManager.GetString("MessageErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave without saving?.
        /// </summary>
        public static string MessageLeaveNoSave {
            get {
                return ResourceManager.GetString("MessageLeaveNoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageTitleError {
            get {
                return ResourceManager.GetString("MessageTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageTitleWarning {
            get {
                return ResourceManager.GetString("MessageTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles per gallon.
        /// </summary>
        public static string MilesPerGallon {
            get {
                return ResourceManager.GetString("MilesPerGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpg.
        /// </summary>
        public static string MilesPerGallonShort {
            get {
                return ResourceManager.GetString("MilesPerGallonShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles per liter.
        /// </summary>
        public static string MilesPerLiter {
            get {
                return ResourceManager.GetString("MilesPerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpl.
        /// </summary>
        public static string MilesPerLiterShort {
            get {
                return ResourceManager.GetString("MilesPerLiterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string MilesShort {
            get {
                return ResourceManager.GetString("MilesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles Since Last.
        /// </summary>
        public static string MilesSinceDisplayName {
            get {
                return ResourceManager.GetString("MilesSinceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month.
        /// </summary>
        public static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 month.
        /// </summary>
        public static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 month.
        /// </summary>
        public static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 month.
        /// </summary>
        public static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months or Kilometers Since Last.
        /// </summary>
        public static string MonthsOrKilometersSinceDisplayName {
            get {
                return ResourceManager.GetString("MonthsOrKilometersSinceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months or Miles Since Last.
        /// </summary>
        public static string MonthsOrMilesSinceDisplayName {
            get {
                return ResourceManager.GetString("MonthsOrMilesSinceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mo.
        /// </summary>
        public static string MonthsShort {
            get {
                return ResourceManager.GetString("MonthsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months Since Last.
        /// </summary>
        public static string MonthsSinceDisplayName {
            get {
                return ResourceManager.GetString("MonthsSinceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mtd.
        /// </summary>
        public static string MTD {
            get {
                return ResourceManager.GetString("MTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tires - New.
        /// </summary>
        public static string NewTiresDisplayName {
            get {
                return ResourceManager.GetString("NewTiresDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneDisplayName {
            get {
                return ResourceManager.GetString("NoneDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string NormalView {
            get {
                return ResourceManager.GetString("NormalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer.
        /// </summary>
        public static string OdometerDisplayName {
            get {
                return ResourceManager.GetString("OdometerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Change.
        /// </summary>
        public static string OilChangeDisplayName {
            get {
                return ResourceManager.GetString("OilChangeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will overwrite the data on your device which cannot be recovered. Are you sure you wish to load your data from online?.
        /// </summary>
        public static string OneDriveAreYouSureLoad {
            get {
                return ResourceManager.GetString("OneDriveAreYouSureLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will overwrite the data online which cannot be recovered. Are you sure you wish to save your data online?.
        /// </summary>
        public static string OneDriveAreYouSureSave {
            get {
                return ResourceManager.GetString("OneDriveAreYouSureSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string OneDriveFileLoading {
            get {
                return ResourceManager.GetString("OneDriveFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loaded successfully..
        /// </summary>
        public static string OneDriveFileLoadSuccessful {
            get {
                return ResourceManager.GetString("OneDriveFileLoadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file did not load properly. Please exit My Car Log and try again..
        /// </summary>
        public static string OneDriveFileLoadUnsuccessful {
            get {
                return ResourceManager.GetString("OneDriveFileLoadUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCarLog.txt was not found online. Please save before accessing..
        /// </summary>
        public static string OneDriveFileNotFound {
            get {
                return ResourceManager.GetString("OneDriveFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        public static string OneDriveFileSaveSuccessful {
            get {
                return ResourceManager.GetString("OneDriveFileSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file did not save properly. Please exit My Car Log and try again..
        /// </summary>
        public static string OneDriveFileSaveUnsuccessful {
            get {
                return ResourceManager.GetString("OneDriveFileSaveUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string OneDriveFileSaving {
            get {
                return ResourceManager.GetString("OneDriveFileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherDisplayName {
            get {
                return ResourceManager.GetString("OtherDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per gallon.
        /// </summary>
        public static string PerGallon {
            get {
                return ResourceManager.GetString("PerGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per liter.
        /// </summary>
        public static string PerLiter {
            get {
                return ResourceManager.GetString("PerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per gallon.
        /// </summary>
        public static string PerQuantity {
            get {
                return ResourceManager.GetString("PerQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicles.
        /// </summary>
        public static string PivotSubtitleCars {
            get {
                return ResourceManager.GetString("PivotSubtitleCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charts.
        /// </summary>
        public static string PivotSubtitleCharts {
            get {
                return ResourceManager.GetString("PivotSubtitleCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuel log.
        /// </summary>
        public static string PivotSubtitleFuelLog {
            get {
                return ResourceManager.GetString("PivotSubtitleFuelLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder log.
        /// </summary>
        public static string PivotSubtitleReminderLog {
            get {
                return ResourceManager.GetString("PivotSubtitleReminderLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service log.
        /// </summary>
        public static string PivotSubtitleServiceLog {
            get {
                return ResourceManager.GetString("PivotSubtitleServiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallons.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        public static string QuantityShort {
            get {
                return ResourceManager.GetString("QuantityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity units.
        /// </summary>
        public static string QuantityUnits {
            get {
                return ResourceManager.GetString("QuantityUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuel Averages.
        /// </summary>
        public static string RefuelAverages {
            get {
                return ResourceManager.GetString("RefuelAverages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string RepairDisplayName {
            get {
                return ResourceManager.GetString("RepairDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Part.
        /// </summary>
        public static string ReplacementPart {
            get {
                return ResourceManager.GetString("ReplacementPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveLocal {
            get {
                return ResourceManager.GetString("SaveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save OneDrive.
        /// </summary>
        public static string SaveOneDrive {
            get {
                return ResourceManager.GetString("SaveOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Maintenance.
        /// </summary>
        public static string ScheduledMaintenanceDisplayName {
            get {
                return ResourceManager.GetString("ScheduledMaintenanceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service event.
        /// </summary>
        public static string ServiceEvent {
            get {
                return ResourceManager.GetString("ServiceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make.
        /// </summary>
        public static string SubtitleMake {
            get {
                return ResourceManager.GetString("SubtitleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model.
        /// </summary>
        public static string SubtitleModel {
            get {
                return ResourceManager.GetString("SubtitleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string SubtitleName {
            get {
                return ResourceManager.GetString("SubtitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting odometer.
        /// </summary>
        public static string SubtitleStartingOdometer {
            get {
                return ResourceManager.GetString("SubtitleStartingOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vin.
        /// </summary>
        public static string SubtitleVIN {
            get {
                return ResourceManager.GetString("SubtitleVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string SubtitleYear {
            get {
                return ResourceManager.GetString("SubtitleYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tires - Repair.
        /// </summary>
        public static string TireRepairDisplayName {
            get {
                return ResourceManager.GetString("TireRepairDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Costs.
        /// </summary>
        public static string TotalCosts {
            get {
                return ResourceManager.GetString("TotalCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string ViewSetting {
            get {
                return ResourceManager.GetString("ViewSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.onmydevice.com.
        /// </summary>
        public static string WebsiteText {
            get {
                return ResourceManager.GetString("WebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.onmydevice.com.
        /// </summary>
        public static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ytd.
        /// </summary>
        public static string YTD {
            get {
                return ResourceManager.GetString("YTD", resourceCulture);
            }
        }
    }
}
